### ISSUE TITLE
install出问题，求助

### ISSUE THREAD

**Issue by wzfxue** [ttian99/unpack-wxapkg#1]
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'unpack-wxapkg' ]
2 info using npm@5.6.0
3 info using node@v9.10.0
4 warn invalid config proxy=""
5 warn invalid config Must be a full url with 'http://'
6 warn invalid config https-proxy=""
7 warn invalid config Must be a full url with 'http://'
8 verbose npm-session 2e6586a91ca1da5d
9 silly install loadCurrentTree
10 silly install readLocalPackageData
11 http fetch GET 304 https://registry.npmjs.org/unpack-wxapkg 569ms (from cache)
12 silly pacote tag manifest for unpack-wxapkg@latest fetched in 611ms
13 silly install loadIdealTree
14 silly install cloneCurrentTreeToIdealTree
15 silly install loadShrinkwrap
16 silly install loadAllDepsIntoIdealTree
17 silly saveTree unpack-wxapkg@1.0.1
17 silly saveTree +-- commander@2.19.0
17 silly saveTree +-- fs-extra@7.0.1
17 silly saveTree | +-- graceful-fs@4.1.15
17 silly saveTree | +-- jsonfile@4.0.0
17 silly saveTree | `-- universalify@0.1.2
17 silly saveTree +-- glob@7.1.3
17 silly saveTree | +-- fs.realpath@1.0.0
17 silly saveTree | +-- inflight@1.0.6
17 silly saveTree | | +-- once@1.4.0
17 silly saveTree | | | `-- wrappy@1.0.2
17 silly saveTree | | `-- wrappy@1.0.2
17 silly saveTree | +-- inherits@2.0.3
17 silly saveTree | +-- minimatch@3.0.4
17 silly saveTree | | `-- brace-expansion@1.1.11
17 silly saveTree | |   +-- balanced-match@1.0.0
17 silly saveTree | |   `-- concat-map@0.0.1
17 silly saveTree | +-- once@1.4.0
17 silly saveTree | `-- path-is-absolute@1.0.1
17 silly saveTree `-- path@0.12.7
17 silly saveTree   +-- process@0.11.10
17 silly saveTree   `-- util@0.10.4
18 verbose stack Error: Refusing to install package with name "unpack-wxapkg" under a package
18 verbose stack also called "unpack-wxapkg". Did you name your project the same
18 verbose stack as the dependency you're installing?
18 verbose stack
18 verbose stack For more information, see:
18 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
18 verbose stack     at checkSelf (E:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:64:14)
18 verbose stack     at Array.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
18 verbose stack     at LOOP (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
18 verbose stack     at E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
18 verbose stack     at hasMinimumFields (E:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:30:12)
18 verbose stack     at Array.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
18 verbose stack     at LOOP (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
18 verbose stack     at chain (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
18 verbose stack     at E:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
18 verbose stack     at E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
18 verbose stack     at Array.forEach (<anonymous>)
18 verbose stack     at E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
18 verbose stack     at Array.forEach (<anonymous>)
18 verbose stack     at asyncMap (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
18 verbose stack     at module.exports (E:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:15:3)
18 verbose stack     at Array.<anonymous> (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose cwd F:\JAVA_WORK\USER_WORK\weixin_work\unpack-wxapkg-master
20 verbose Windows_NT 6.1.7601
21 verbose argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "unpack-wxapkg"
22 verbose node v9.10.0
23 verbose npm  v5.6.0
24 error code ENOSELF
25 error Refusing to install package with name "unpack-wxapkg" under a package
25 error also called "unpack-wxapkg". Did you name your project the same
25 error as the dependency you're installing?
25 error
25 error For more information, see:
25 error     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
26 verbose exit [ 1, true ]

**Comment by wzfxue** [comment]
> 0 info it worked if it ends with ok
> 1 verbose cli [ 'E:\Program Files\nodejs\node.exe',
> 1 verbose cli 'E:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
> 1 verbose cli 'i',
> 1 verbose cli 'unpack-wxapkg' ]
> 2 info using npm@5.6.0
> 3 info using node@v9.10.0
> 4 warn invalid config proxy=""
> 5 warn invalid config Must be a full url with 'http://'
> 6 warn invalid config https-proxy=""
> 7 warn invalid config Must be a full url with 'http://'
> 8 verbose npm-session 2e6586a91ca1da5d
> 9 silly install loadCurrentTree
> 10 silly install readLocalPackageData
> 11 http fetch GET 304 https://registry.npmjs.org/unpack-wxapkg 569ms (from cache)
> 12 silly pacote tag manifest for unpack-wxapkg@latest fetched in 611ms
> 13 silly install loadIdealTree
> 14 silly install cloneCurrentTreeToIdealTree
> 15 silly install loadShrinkwrap
> 16 silly install loadAllDepsIntoIdealTree
> 17 silly saveTree unpack-wxapkg@1.0.1
> 17 silly saveTree +-- commander@2.19.0
> 17 silly saveTree +-- fs-extra@7.0.1
> 17 silly saveTree | +-- graceful-fs@4.1.15
> 17 silly saveTree | +-- jsonfile@4.0.0
> 17 silly saveTree | `-- universalify@0.1.2 17 silly saveTree +-- glob@7.1.3 17 silly saveTree | +-- fs.realpath@1.0.0 17 silly saveTree | +-- inflight@1.0.6 17 silly saveTree | | +-- once@1.4.0 17 silly saveTree | | | `-- wrappy@1.0.2
> 17 silly saveTree | | `-- wrappy@1.0.2 17 silly saveTree | +-- inherits@2.0.3 17 silly saveTree | +-- minimatch@3.0.4 17 silly saveTree | | `-- brace-expansion@1.1.11
> 17 silly saveTree | | +-- balanced-match@1.0.0
> 17 silly saveTree | | `-- concat-map@0.0.1 17 silly saveTree | +-- once@1.4.0 17 silly saveTree | `-- path-is-absolute@1.0.1
> 17 silly saveTree `-- path@0.12.7 17 silly saveTree +-- process@0.11.10 17 silly saveTree `-- util@0.10.4
> 18 verbose stack Error: Refusing to install package with name "unpack-wxapkg" under a package
> 18 verbose stack also called "unpack-wxapkg". Did you name your project the same
> 18 verbose stack as the dependency you're installing?
> 18 verbose stack
> 18 verbose stack For more information, see:
> 18 verbose stack https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm
> 18 verbose stack at checkSelf (E:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:64:14)
> 18 verbose stack at Array. (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
> 18 verbose stack at LOOP (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
> 18 verbose stack at E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
> 18 verbose stack at hasMinimumFields (E:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:30:12)
> 18 verbose stack at Array. (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
> 18 verbose stack at LOOP (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
> 18 verbose stack at chain (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
> 18 verbose stack at E:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
> 18 verbose stack at E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
> 18 verbose stack at Array.forEach ()
> 18 verbose stack at E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:11
> 18 verbose stack at Array.forEach ()
> 18 verbose stack at asyncMap (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:51:8)
> 18 verbose stack at module.exports (E:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:15:3)
> 18 verbose stack at Array. (E:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
> 19 verbose cwd F:\JAVA_WORK\USER_WORK\weixin_work\unpack-wxapkg-master
> 20 verbose Windows_NT 6.1.7601
> 21 verbose argv "E:\Program Files\nodejs\node.exe" "E:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "i" "unpack-wxapkg"
> 22 verbose node v9.10.0
> 23 verbose npm v5.6.0
> 24 error code ENOSELF
> 25 error Refusing to install package with name "unpack-wxapkg" under a package
> 25 error also called "unpack-wxapkg". Did you name your project the same
> 25 error as the dependency you're installing?
> 25 error
> 25 error For more information, see:
> 25 error https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm
> 26 verbose exit [ 1, true ]

通过bin/cmd 改为js，在windows下node cmd.js 可以用。
执行到unpackWxapkg over不动了，输出目录中好像并无解包之后的文件。

**Comment by ttian99** [comment]
### @wzfxue 感谢你的反馈。
### 1.install失败的问题：
我这边暂时没法复现你的问题，所以还需要研究一下。不过看你的log，是你在已经有一个项目名为unpack-wxapkg项目下面，再去安装unpack-wxapkg包，导致npm报错。请尝试先移除重名的unpack-wxapkg文件夹，再安装试试。
### 2.输出目录无解压包：
是由于程序里面用到了```__dirname```来定位目录，而全局安装后，unpack-wxapkg包的目录位于npm的全局安装包目录下了：```C:\Users\{用户名}\AppData\Roaming\npm\node_modules\unpack-wxapkg```。这个问题在**新的版本v1.0.2里面修复了**。

**Comment by wzfxue** [comment]
> ### @wzfxue 感谢你的反馈。
> ### 1.install失败的问题：
> 我这边暂时没法复现你的问题，所以还需要研究一下。不过看你的log，是你在已经有一个项目名为unpack-wxapkg项目下面，再去安装unpack-wxapkg包，导致npm报错。请尝试先移除重名的unpack-wxapkg文件夹，再安装试试。
> 
> ### 2.输出目录无解压包：
> 是由于程序里面用到了`__dirname`来定位目录，而全局安装后，unpack-wxapkg包的目录位于npm的全局安装包目录下了：`C:\Users\{用户名}\AppData\Roaming\npm\node_modules\unpack-wxapkg`。这个问题在**新的版本v1.0.2里面修复了**。

---------------------------------------------

F:\JAVA_WORK\USER_WORK\weixin_work\unpack-wxapkg-master\bin>node cmd.js -s F:\JA
VA_WORK\USER_WORK\weixin_work\unpack-wxapkg-master\test -d F:\JAVA_WORK\USER_WOR
K\weixin_work\kaoqingtong\pack\out
src = F:\JAVA_WORK\USER_WORK\weixin_work\unpack-wxapkg-master\test , dest = F:\J
AVA_WORK\USER_WORK\weixin_work\kaoqingtong\pack\out
unpackWxapkg start: F:/JAVA_WORK/USER_WORK/weixin_work/unpack-wxapkg-master/test
/yours.wxapkg
fileCount = 55
fileName - /img/canvas_mask.png
fileName - /img/daren.ccef5c76.png
fileName - /img/default.png
fileName - /img/default_head.png
fileName - /img/guanfang.309504f8.png
fileName - /img/icon-cancel.png
fileName - /img/icon-loading.png
fileName - /img/icon-message.d8831382.png
fileName - /img/icon-play.png
fileName - /img/icon-search.png
fileName - /img/icon_edit.cc58fb6c.png
fileName - /img/icon_face.cd2bf3a7.png
fileName - /img/img-close.png
fileName - /img/link_icon.png
fileName - /img/loading.png
fileName - /img/owner.a2c84211.png
fileName - /img/penguin.4f7f0cb8.png
fileName - /img/pic.55166d3b.png
fileName - /img/renzheng.0aac90e7.png
fileName - /img/style-emoji.png
fileName - /img/warn_big.f4628d84.png
fileName - /pages/index/background.svg
fileName - /app-config.json
fileName - /app-service.js
fileName - /common/wxParse/wxParse.html
fileName - /components/component_url/url.html
fileName - /components/component_video/video.html
fileName - /components/float_guide/full.html
fileName - /components/float_guide/tiny.html
fileName - /components/navigation_bar/index.html
fileName - /components/smiley/smiley.html
fileName - /pages/all_circles/all_circles.html
fileName - /pages/club_detail/canvas_img.html
fileName - /pages/club_detail/club_detail.html
fileName - /pages/club_detail/manage.html
fileName - /pages/club_index/club_index.html
fileName - /pages/club_index/strategy_list.html
fileName - /pages/club_index/topic_list.html
fileName - /pages/cluster_topic/cluster_list.html
fileName - /pages/cluster_topic/cluster_topic.html
fileName - /pages/cluster_topic/more_cluster.html
fileName - /pages/editor/editor.html
fileName - /pages/editor/index.html
fileName - /pages/index/index.html
fileName - /pages/more_circles/more_circles.html
fileName - /pages/publish/preview.html
fileName - /pages/publish/publish.html
fileName - /pages/publish/reply.html
fileName - /pages/search/search.html
fileName - /pages/special_topic/special_topic.html
fileName - /pages/video/qtvideo.html
fileName - /pages/video/video.html
fileName - /pages/webview/webview.html
fileName - /pages/webview_share/webview.html
fileName - /page-frame.html
unpackWxapkg over

这样指定的输出目录，然后我去C:\Users\{用户名}\AppData\Roaming\npm\node_modules\unpack-wxapkg这个目录也没有。
请问是否解包之后没有分包处理，还原出wxss,wxml等？

**Comment by ttian99** [comment]
- 1.已经指定了输出目录：
- 2.本工具目前只做了将wxapkg解析操作，得到合并输出的js和html等文件，暂时还不能还原到wxss，wxml等可编译的程度。
- 另外，新的v1.0.2版本已经发布到npm了，你可以使用新版本

**Comment by wzfxue** [comment]
> * 1.已经指定了输出目录：
> * 2.本工具目前只做了将wxapkg解析操作，得到合并输出的js和html等文件，暂时还不能还原到wxss，wxml等可编译的程度。
> * 另外，新的v1.0.2版本已经发布到npm了，你可以使用新版本

好的，谢谢。希望能出来可以还原wxss,xml的功能。

**Comment by wzfxue** [comment]
> > * 1.已经指定了输出目录：
> > * 2.本工具目前只做了将wxapkg解析操作，得到合并输出的js和html等文件，暂时还不能还原到wxss，wxml等可编译的程度。
> > * 另外，新的v1.0.2版本已经发布到npm了，你可以使用新版本
> 
> 好的，谢谢。希望能出来可以还原wxss,xml的功能。

倒是手工还原成功了

**Comment by ttian99** [comment]
> > > * 1.已经指定了输出目录：
> > > * 2.本工具目前只做了将wxapkg解析操作，得到合并输出的js和html等文件，暂时还不能还原到wxss，wxml等可编译的程度。
> > > * 另外，新的v1.0.2版本已经发布到npm了，你可以使用新版本
> > 
> > 
> > 好的，谢谢。希望能出来可以还原wxss,xml的功能。
> 
> 倒是手工还原成功了

可以，可以！
